[Settings]
ID = "Your_Site_ID"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "demo/index.html"

# A basic redirects rule
# [[redirects]]
#   from = "/*"
#   to = "/blog/:splat"



# The following redirect is intended for use with most SPA's that handles routing internally.
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# [[headers]]
#   for = "/*" # This defines which paths this specific [[headers]] block will cover.
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
#     Content-Security-Policy = "frame-ancestors https://www.facebook.com"
#     # Multi-key header rules are expressed with multi-line strings
#     Link = '''
#     </assets/css/base.css>; rel=preload; as=style, \
#     </assets/css/base2.css>; rel=preload; as=style, \
#     </assets/css/base3.css>; rel=preload; as=style'''
#     # Basic-Auth allows you to password protect your whole site but is only available
#     # to paid accounts
#     Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"